# fly.toml file generated for fortune on 2021-04-09T20:18:32+08:00

app = "fortune"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 8000
protocol = "tcp"

[build]
image = "fortune"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.http_checks]]
grace_period = "20s"
interval = "15s"
method = "get"
path = "/api/version"
protocol = "https"
restart_limit = 6
timeout = "2s"