# fly.toml file generated for fortune on 2021-04-09T20:18:32+08:00

app = "fortune"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 8000
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.http_checks]]
grace_period = "30s"
interval = "30s"
method = "get"
path = "/api/version"
protocol = "http"
restart_limit = 6
timeout = "5s"